### ISSUE TITLE
Current version of Windows Binary fails locally on Win10/x64

### ISSUE THREAD

**Issue by rokreis** [microsoft/sbom-tool#181]
Dear all, 

I tried to run the provided binary, but it seems it has a mixture of families (x32, x64), but maybe I'm just wrong.
Here the stacktrace after just running the binary locally:

--- SNIP ---
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.BadImageFormatException:
File name: 'C:\Users\<USERNAME>\AppData\Local\Temp\.net\sbom-tool-win-x64\mKUTLbqWlQzcwLm3HUQsFUT02rtVQ8c=\libMonoPosixHelper.dll'
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Microsoft.Sbom.Api.Bindings.<>c.<Load>b__0_8[T](String x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Sbom.Api.Bindings.<>c__DisplayClass0_0.<Load>g__BindAllTypesThatImplement|2[T](String[] partialAssemblyNames)
   at Microsoft.Sbom.Api.Bindings.Load()
   at Ninject.Modules.NinjectModule.OnLoad(IKernel kernel)
   at Ninject.KernelBase.Load(IEnumerable`1 m)
   at Ninject.KernelBase..ctor(IComponentContainer components, INinjectSettings settings, INinjectModule[] modules)
   at Ninject.KernelBase..ctor(INinjectModule[] modules)
   at Ninject.StandardKernel..ctor(INinjectModule[] modules)
   at Microsoft.Sbom.Api.Config.SbomToolCmdRunner..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at PowerArgs.ObjectFactory.CreateInstance(Type t)
   at PowerArgs.Args.ParseInternal(CommandLineArgumentsDefinition definition, String[] input)
   at PowerArgs.Args.<>c__DisplayClass17_1.<InvokeAction>b__3()
   at PowerArgs.Args.Execute[T](Func`1 argsProcessingCode)
   at PowerArgs.Args.<>c__DisplayClass17_0.<InvokeAction>b__2(String[] a)
   at PowerArgs.REPL.DriveREPL[T](TabCompletion t, Func`2 eval, String[] args, Func`1 defaultEval)
   at PowerArgs.Args.InvokeAction(CommandLineArgumentsDefinition definition, String[] args)
   at PowerArgs.Args.InvokeAction[T](String[] args)
   at PowerArgs.Args.<>c__DisplayClass32_0`1.<InvokeActionAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Sbom.Tool.Program.Main(String[] args)
   at Microsoft.Sbom.Tool.Program.<Main>(String[] args)
--- SNAP ----

**Comment by aasim** [comment]
This issue has been fixed in version 0.3.1
