### ISSUE TITLE
Test failures on Linux

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/sbom-tool#194]
I am trying to package `sbom-tool` for [NixOS][1] and I am seeing the following test failures:

<details>
<summary>ManifestFolderFilterTest_CheckAllManifestFolder_Succeeds</summary>

```
Error Message:
   Assert.IsFalse failed. 
  Stack Trace:
     at Microsoft.Sbom.Api.Filters.Tests.ManifestFolderFilterTests.ManifestFolderFilterTest_CheckAllManifestFolder_Succeeds() in /build/source/test/Microsoft.Sbom.Api.Tests/Filters/ManifestFolderFilterTests.cs:line 37
```

</details>

<details>
<summary>SbomToolManifestPathConverterTests_ValidPath_Succeeds</summary>

```
Error Message:
   Assert.AreEqual failed. Expected:</hello/World>. Actual:</../C:/Sample/Root/hello/World>. 
  Stack Trace:
     at Microsoft.Sbom.Api.Convertors.Tests.SbomToolManifestPathConverterTests.SbomToolManifestPathConverterTests_ValidPath_Succeeds() in /build/source/test/Microsoft.Sbom.Api.Tests/Converters/SbomToolManifestPathConverterTests.cs:line 57
```

</details>

<details>
<summary>SbomToolManifestPathConverterTests_ValidPathWithDot_Succeeds</summary>

```
Error Message:
   Assert.AreEqual failed. Expected:</hello/World>. Actual:</../C:/Sample/Root/./hello/./World>. 
  Stack Trace:
     at Microsoft.Sbom.Api.Convertors.Tests.SbomToolManifestPathConverterTests.SbomToolManifestPathConverterTests_ValidPathWithDot_Succeeds() in /build/source/test/Microsoft.Sbom.Api.Tests/Converters/SbomToolManifestPathConverterTests.cs:line 77
```

</details>

<details>
<summary>SbomToolManifestPathConverterTests_BuildDropPathRelative_Succeeds</summary>

```
Error Message:
   Assert.AreEqual failed. Expected:</hello/World>. Actual:</../Sample/./Root//hello/./World>. 
  Stack Trace:
     at Microsoft.Sbom.Api.Convertors.Tests.SbomToolManifestPathConverterTests.SbomToolManifestPathConverterTests_BuildDropPathRelative_Succeeds() in /build/source/test/Microsoft.Sbom.Api.Tests/Converters/SbomToolManifestPathConverterTests.cs:line 97
```

</details>

<details>
<summary>SbomToolManifestPathConverterTests_CaseSensitive_Windows_FreeBSD_Succeeds</summary>

```
Error Message:
   Assert.AreEqual failed. Expected:</hello/World>. Actual:</../C:/sample/Root/hello/World>. 
  Stack Trace:
     at Microsoft.Sbom.Api.Convertors.Tests.SbomToolManifestPathConverterTests.SbomToolManifestPathConverterTests_CaseSensitive_Windows_FreeBSD_Succeeds() in /build/source/test/Microsoft.Sbom.Api.Tests/Converters/SbomToolManifestPathConverterTests.cs:line 117
```

</details>

<details>
<summary>SbomToolManifestPathConverterTests_RootPathOutside_SbomOnDifferentDrive_Succeeds</summary>

```
Error Message:
   Assert.AreEqual failed. Expected:</d:/Root/hello/World.spdx.json>. Actual:</../d:/Root/hello/World.spdx.json>. 
  Stack Trace:
     at Microsoft.Sbom.Api.Convertors.Tests.SbomToolManifestPathConverterTests.SbomToolManifestPathConverterTests_RootPathOutside_SbomOnDifferentDrive_Succeeds() in /build/source/test/Microsoft.Sbom.Api.Tests/Converters/SbomToolManifestPathConverterTests.cs:line 168
```

</details>

<details>
<summary>SbomToolManifestPathConverterTests_RootPathOutside_SbomOnSameDrive_Succeeds</summary>

```
Error Message:
   Assert.AreEqual failed. Expected:</../hello/World.spdx.json>. Actual:</../C:/Sample/hello/World.spdx.json>. 
  Stack Trace:
     at Microsoft.Sbom.Api.Convertors.Tests.SbomToolManifestPathConverterTests.SbomToolManifestPathConverterTests_RootPathOutside_SbomOnSameDrive_Succeeds() in /build/source/test/Microsoft.Sbom.Api.Tests/Converters/SbomToolManifestPathConverterTests.cs:line 181
```

</details>

[1]: https://nixos.org/

**Comment by edgarrs** [comment]
@ksigmund, are you investigating this issue?

**Comment by ksigmund** [comment]
I had created and merged a PR that, during testing for another issue, we found a bug with and ended up reverting.  That's why this issue isn't closed.  https://github.com/microsoft/sbom-tool/pull/208

@sebasgomez238 is going to revert the revert 🙃 and test again to see if he can fix the issue.  If I recall, it may have had to do with validation in Windows.

**Comment by edgarrs** [comment]
This has been fixed in the last release v.1.1.5
