### ISSUE TITLE
File Access Error when passing --DirectoryExclusionList

### ISSUE THREAD

**Issue by sebasgomez238** [microsoft/sbom-tool#438]
If a --DirectoryExclusionList is passed to the tool. It causes the internal exclusion of the _manifest directory to be overwritten and leads to a file access collision.

##[warning]Unhandled exception caught when trying to open "C:\\repos\\Sbom\\_manifest\\spdx_2.2\\manifest.spdx.json"
System.IO.IOException: The process cannot access the file 'C:\repos\Sbom\_manifest\spdx_2.2\manifest.spdx.json' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileInfo.OpenRead()
   at Microsoft.ComponentDetection.Common.LazyComponentStream.SafeOpenFile()

**Comment by sebasgomez238** [comment]
Fix is included as a part of #436
